"""Vocabulary-related agent tools."""

import logging

from langchain.tools import ToolRuntime
from langchain_core.tools import tool
from pydantic import BaseModel, Field, field_validator

from runestone.agents.tools.context import AgentContext
from runestone.agents.tools.service_providers import provide_vocabulary_service

logger = logging.getLogger(__name__)


class WordPrioritisationItem(BaseModel):
    """Input for a single word to save for future learning."""

    word_phrase: str = Field(..., description="The Swedish word or phrase")
    translation: str = Field(..., description="Translation of the word_phrase (concise)")
    example_phrase: str = Field(..., description="Example sentence in Swedish")

    @field_validator("word_phrase", "translation", "example_phrase", mode="before")
    @classmethod
    def decode_unicode_escapes(cls, v: str) -> str:
        """Fix double-escaped unicode characters often generated by LLMs."""
        if isinstance(v, str) and "\\u" in v:
            try:
                # v.encode('utf-8') converts 'f\\u00f6...' to bytes b'f\\u00f6...'
                # .decode('unicode_escape') interprets \\u00f6 as ö
                return v.encode("utf-8").decode("unicode_escape")
            except Exception:
                return v
        return v


class WordPrioritisationInput(BaseModel):
    """Input for saving useful words for future learning and priority recall."""

    words: list[WordPrioritisationItem] = Field(..., description="List of useful words to save and prioritize")


@tool(args_schema=WordPrioritisationInput)
async def prioritize_words_for_learning(
    words: list[WordPrioritisationItem],
    runtime: ToolRuntime[AgentContext],
) -> str:
    """
    Save useful/interesting words for future learning and mark them for priority recall.
    Use during normal conversation whenever the student asks to save vocabulary
    or when a word is clearly worth practicing later.

    For each word:
    - If deleted: restores it and marks for priority
    - If exists: marks for priority (or confirms already prioritized)
    - If new: creates it with priority flag

    Args:
        words: List of words to save and prioritize for learning
        runtime: Tool runtime context

    Returns:
        Confirmation message with per-action summary
    """
    user = runtime.context.user

    processed_count = 0
    errors = []
    action_counts = {
        "created": 0,
        "restored": 0,
        "prioritized": 0,
        "already_prioritized": 0,
    }

    if not words:
        logger.warning("prioritize_words_for_learning called with empty words list for user_id=%s", user.id)
        return "No words were provided for priority learning."

    logger.info("Starting prioritize_words_for_learning for user_id=%s with %s words", user.id, len(words))

    # Use fresh service with its own session for concurrency safety
    async with provide_vocabulary_service() as vocab_service:
        for word_item in words:
            try:
                result = await vocab_service.upsert_priority_word(
                    word_phrase=word_item.word_phrase,
                    translation=word_item.translation,
                    example_phrase=word_item.example_phrase,
                    user_id=user.id,
                )
                action = str(result.get("action", "prioritized"))
                if action not in action_counts:
                    action = "prioritized"
                action_counts[action] += 1
                logger.info(
                    "Processed priority word: word='%s', user_id=%s, action=%s, word_id=%s, changed=%s",
                    word_item.word_phrase,
                    user.id,
                    action,
                    result.get("word_id"),
                    result.get("changed"),
                )
                processed_count += 1
            except Exception as e:
                logger.exception(
                    "Failed to process priority word: word='%s', user_id=%s",
                    word_item.word_phrase,
                    user.id,
                )
                # Keep processing remaining words with the same session.
                # SQLAlchemy sessions require rollback after failed flush/commit.
                await vocab_service.repo.db.rollback()
                errors.append(f"{word_item.word_phrase}: {str(e)}")

    summary = (
        f"created={action_counts['created']}, restored={action_counts['restored']}, "
        f"prioritized={action_counts['prioritized']}, already_prioritized={action_counts['already_prioritized']}"
    )
    logger.info(
        "Finished prioritize_words_for_learning for user_id=%s: processed=%s, %s, errors=%s",
        user.id,
        processed_count,
        summary,
        len(errors),
    )

    if errors:
        error_msg = "; ".join(errors)
        return f"Processed {processed_count} word(s): {summary}. Errors: {error_msg}"

    return f"Successfully processed {processed_count} word(s): {summary}."
