"""Shared cross-layer constants."""

MEMORY_DEFAULT_AREA_TO_IMPROVE_PRIORITY = 9

# Vocabulary priority model (0 = highest, 9 = lowest/default)
VOCABULARY_PRIORITY_HIGH = 0
VOCABULARY_PRIORITY_AGENT_NEW = 4
VOCABULARY_PRIORITY_LEGACY_TRUE_BACKFILL = 5
VOCABULARY_PRIORITY_LOW = 9
VOCABULARY_PRIORITY_DEFAULT = VOCABULARY_PRIORITY_LOW
