"""add chat tables

Revision ID: d669959e47fc
Revises: 26f00047b2cb
Create Date: 2026-01-04 22:49:53.736110

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d669959e47fc"
down_revision: Union[str, Sequence[str], None] = "26f00047b2cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_messages_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_messages_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_messages_user_id"), ["user_id"], unique=False)

    op.create_table(
        "chat_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("summary_content", sa.Text(), nullable=False),
        sa.Column("last_message_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_summaries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_summaries_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_summaries_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("chat_summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_summaries_user_id"))
        batch_op.drop_index(batch_op.f("ix_chat_summaries_id"))

    op.drop_table("chat_summaries")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_user_id"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_id"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_created_at"))

    op.drop_table("chat_messages")
    # ### end Alembic commands ###
